version: '3.8'

services:
  traefik:
    image: traefik:2.11
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=benjamin.buelow@walkingcows.de
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_static
    volumes:
      - ./static:/usr/share/nginx/html:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`walkingcows.de`)
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.routers.nginx.tls.certresolver=le
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.nginx-redirect.rule=Host(`walkingcows.de`)
      - traefik.http.routers.nginx-redirect.entrypoints=web
      - traefik.http.routers.nginx-redirect.middlewares=redirect-to-https
    restart: unless-stopped
